service: starwars-api

plugins:
  - serverless-jetpack
  - serverless-offline

useDotenv: true

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    SWAPI_URL: ${env:SWAPI_URL}
    DATABASE_URL: ${env:DATABASE_URL}
  # stage: production
  # region: us-east-1
  # memorySize: 2048
  vpc:
    subnetIds:
      - subnet-0bf79a58960460c7e
      - subnet-055feaddca913028c
      - subnet-0e17a2d20a160af93
      - subnet-0dddebcd6bb360117
      - subnet-0ffdbdde1b7f4cbec
      - subnet-0b9b7771bef7496d9
    securityGroupIds:
      - sg-0565b976b97262683
  apiGateway:
    name: starwars-api-gateway 
    version: v2
    cors:
      origins:
        - '*'
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - HEAD
      headers:
        - Content-Type
        - Authorization
      allowCredentials: false

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: '{proxy+}'
          method: ANY
    vpc:
      subnetIds:
        - subnet-0bf79a58960460c7e
        - subnet-055feaddca913028c
        - subnet-0e17a2d20a160af93
        - subnet-0dddebcd6bb360117
        - subnet-0ffdbdde1b7f4cbec
        - subnet-0b9b7771bef7496d9
      securityGroupIds:
        - sg-0565b976b97262683

package:
  include:
    - '!node_modules/.prisma/client/**'
    - 'node_modules/.prisma/client/**'
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
    - '!node_modules/.cache/prisma/**'  